name: Deploy React App to Azure App Service

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep to Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group rg-CDC-team \
              --template-file ./infrastructure/main.bicep \
              --parameters location="KoreaCentral"

  build_and_deploy_app:
    needs: deploy_infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure App Service
        run: |
          az webapp deploy --resource-group rg-CDC-team \
                           --name my-react-app \
                           --src-path ./build \
                           --type static
